### ISSUE TITLE
Question: Difficulty of FP8 + ZeRO

### ISSUE THREAD

**Issue by awgu** [Azure/MS-AMP#108]
>  Directly applying FP8 to ZeRO is infeasible, because it is difficult to handle the scaling factors associated with the FP8 partitions. The per-tensor scaling factors should be distributed along with FP8 partitions. [...]  In this way, the tensor scaling factors can be distributed along with the tensors smoothly, while reducing communication and compute complexity

from page 7 of https://arxiv.org/pdf/2310.18313.pdf

I wanted to clarify exactly what is the challenge with the original ZeRO partitioning that is intra-parameter. Is the challenge solely a _performance_ challenge (namely, (1) communicating scaling factors and (2) requiring scale computation for a single logical parameter on possibly multiple workers)? Or, are there other non-performance-related challenges as well?

---

> Furthermore, in ZeRO distributed training, our method distributes each FP8 tensor along with its associated scaling factor as a whole, rather than partitioning the tensor into splits across GPUs. This strategy not only results in more GPU memory savings but also maintains a balanced memory load across GPUs, as demonstrated in Tab. 8.

I looked at this problem very briefly as an intern a few years ago (https://github.com/pytorch/pytorch/pull/59410), so this design choice was curious to me.

I have not read your implementation, but I was wondering: Would changing from a intra-parameter sharding (like existing ZeRO) to an inter-parameter sharding make it challenging to implement a performant ZeRO-2 or ZeRO-3, where the consideration is that all-gather (for intra-parameter sharding) may be more performant than broadcast/group of broadcast (for inter-parameter sharding)?

Moreover, do you have any concern around the load balancing when the data-parallel degree is larger (e.g. >= 128 GPUs)?

**Comment by wkcn** [comment]
Hi @awgu , thanks for your attention to our work!

1. I believe it's primarily a performance challenge. When updating a tensor with a scaling factor, this factor should be adjusted according to the maximum absolute value across the entire tensor. When the tensor is partitioned across multiple GPUs, extra communication is required to reduce the maximum value. Therefore, we distribute each tensor as a whole across GPUs. 

2. Thank you for providing the valuable information! We employ an inter-parameter sharding on scaling tensors only for ZeRO-1 and ZeRO-2 within DeepSpeed and Megatron-LM. Intra-parameter sharding is kept for high-precision tensors. ZeRO-3 for scaling tensors has not been implemented yet. We did not compare the performance between all-gather and broadcast. We apply all-gather for model weights, which can be found in the following code snippets:
   - [all-gather in Megatron-LM (dtype == torch.uint8)](https://github.com/Azure/MS-AMP/blob/main/msamp/megatron/optimizer/distrib_optimizer.py#L561)
   - [all-gather in DeepSpeed](https://github.com/Azure/MS-AMP/blob/main/msamp/deepspeed/runtime/zero/fp8_stage_1_and_2.py#L747)
   
   There are two key distinctions between scaling tensors and high-precision tensors:
   a. We employ the Greedy Distribution Algorithm for ZeRO (as described in Algorithm 1 in the paper) to partition the scaling tensors across GPUs.
   b. The scaling factors need to be synchronized across GPUs after all-gathering the tensor parts of scaling tensors.

3. The imbalance problem can occur when the number of parameters, including TP partitions, is smaller than the DP degree.
