### ISSUE TITLE
Automatic Scaling in the code

### ISSUE THREAD

**Issue by afcruzs** [Azure/MS-AMP#117]
I'm having a bit of a hard time mapping the equations from the paper to the code. Can you point to where in the code is eq 3?

Essentially, where's mu updated every 1k steps after checking the gradient statistics.

![image](https://github.com/Azure/MS-AMP/assets/4340932/92e810fd-73ee-45a7-abb8-5b325d0c4f8e)

I've gotten so far that `compute_scaling_factor` is rather related to eq 4 and 5

**Comment by wkcn** [comment]
Hi @afcruzs , thanks for your interest of our work!

The code of automatic scaling has not been integrated.
Currently, we simply employ an empircal factor `1 / sqrt(data_parallel_group_size)` to reduce the ratio of overflow and underflow.
https://github.com/Azure/MS-AMP/blob/main/msamp/nn/distributed.py#L149
In automatic scaling, the factor will be tuned automatically along with the ratio of overflow.

**Comment by afcruzs** [comment]
Thanks - this clears it up!
