### ISSUE TITLE
FP8 in linear layer question

### ISSUE THREAD

**Issue by afcruzs** [Azure/MS-AMP#118]
Are the weights of the FP8Linear actually in FP8 or in FP16? - The paper seems to imply so

> To equip tensor parallelism with FP8, we convert the sharded weight and activation tensors to FP8 format for linear layer computation.

- But I was checking the GPT-3 example as far as I can see the `weight_qtype` is float16:  https://github.com/Azure/MS-AMP-Examples/blob/main/gpt3/Megatron-LM.patch#L647
- The underlying tensor in `FP8Linear` gets created consequentially with float16 type: https://github.com/Azure/MS-AMP/blob/main/msamp/nn/linear.py#L35
- However, the `functional` linear override, does cast the weights to FP8 before performing the forward: https://github.com/Azure/MS-AMP/blob/main/msamp/nn/functional.py#L33

So what I understand from this is that the activations are in FP8 but the actual weights are in float16. Am I missing something?

**Comment by wkcn** [comment]
@afcruzs  Thank you for your attention to our work!
And thank @DanBlanaru  for the explanation！

In mixed precision training, there are two components in a linear layer: the master weight and the weight. The master weight is utilized for parameter updating in the optimizer. After the master weight is updated, it is converted into the weight. The weight is employed for computation during both forward and backward passes.

In BF16 mixed precision training, the master weight is an FP32 tensor, while the weight is a BF16 tensor.

For FP8 mixed precision training, the master weight can either be an FP16 tensor with a scaling factor (by default) or an FP32 tensor. The weight is an FP8 tensor with a scaling tensor.


> But I was checking the GPT-3 example as far as I can see the weight_qtype is float16: https://github.com/Azure/MS-AMP-Examples/blob/main/gpt3/Megatron-LM.patch#L647

The second argument of `LinearReplacer.replace` is the data type of the master weight. The master weight is an FP16 with an scaling factor, and the weight is a FP8 tensor with an scaling factor.

> The underlying tensor in FP8Linear gets created consequentially with float16 type: https://github.com/Azure/MS-AMP/blob/main/msamp/nn/linear.py#L35

It is a master weight. When training a model with ZeRO, the weight will be replaced with an FP8 tensor with a scaling factor, and the optimizer stores the FP16 master weight with a scaling factor.

https://github.com/Azure/MS-AMP/blob/main/msamp/deepspeed/runtime/zero/fp8_stage_1_and_2.py#L93

> However, the functional linear override, does cast the weights to FP8 before performing the forward: https://github.com/Azure/MS-AMP/blob/main/msamp/nn/functional.py#L33

The master weight (an FP16 tensor with a scaling factor) is converted to the weight (an FP8 tensor with a scaling factor).
