### ISSUE TITLE
FP8 in tensor parallel region question

### ISSUE THREAD

**Issue by afcruzs** [Azure/MS-AMP#119]
Hello, I have a couple of questions about the FP8 operations circled in the Fig 2. from the paper:

![image](https://github.com/Azure/MS-AMP/assets/4340932/7f100e3c-0c28-43bc-b9a1-ff27134387a8)

- First green circle: In Megatron-LM (eg [gpt-3 example](https://github.com/Azure/MS-AMP-Examples/blob/main/gpt3/Megatron-LM.patch#L647)) where does the conversion to FP8 happens after the layer-norm? 
- For the pink circle, why do we need to convert to FP8 again, doesn't the `g` op already gives us the results in FP8?
- For the blue circle, why do we need to cast here again? As I understood the [LinearReplacer](https://github.com/Azure/MS-AMP-Examples/blob/main/gpt3/Megatron-LM.patch#L647) it replaces all the `nn.Linear` modules, this should include the linear layer *before* the GELU, so the output of such layer should be already in FP8, no?

I suspect I'm misunderstanding the convention of the "FP8 low-bit" orange box in the image, I'd appreciate if you can help me clear up my confusion :)

**Comment by wkcn** [comment]
Hi @afcruzs , thanks for your attention to our work!

> First green circle: In Megatron-LM (eg [gpt-3 example](https://github.com/Azure/MS-AMP-Examples/blob/main/gpt3/Megatron-LM.patch#L647)) where does the conversion to FP8 happens after the layer-norm?

The output of LayerNorm will be converted to FP8. Then it is gathered in the tensor parallelism group on the dimension of sequence length.

> For the pink circle, why do we need to convert to FP8 again, doesn't the g op already gives us the results in FP8?

It is not a conversion. We declare it is a FP8 tensor, which is the output of gathering (i.e. the operation g) FP8 activation.

> For the blue circle, why do we need to cast here again? As I understood the [LinearReplacer](https://github.com/Azure/MS-AMP-Examples/blob/main/gpt3/Megatron-LM.patch#L647) it replaces all the nn.Linear modules, this should include the linear layer before the GELU, so the output of such layer should be already in FP8, no?

The output of GELU is a BF16 tensor, which will be conveted to an FP8 tensor with a scaling factor, serving as the input of FP8Linear.
If the input of a FP8Linear is an FP8 tensor with a scaling factor, there is no further FP8 conversion for the input.

**Comment by afcruzs** [comment]
From the code point of view, is the fp8 conversion from the layernorm output happening in the layernorm torch module itself or somewhere else? Maybe directly on the input of the of the gathering operation? I couldn't find it (for the gpt3 example)

**Comment by wkcn** [comment]
@afcruzs MS-AMP can be used with Transformer Engine, and the FP8 conversion is done here.
https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/module/layernorm_linear.py#L141

If not using the transformer block in Transformer Engine, the FP8 conversion will be done in the FP8Linear.
https://github.com/Azure/MS-AMP/blob/main/msamp/nn/functional.py#L32

**Comment by afcruzs** [comment]
Thanks a lot for the pointers!
