### ISSUE TITLE
question about the paper

### ISSUE THREAD

**Issue by WeiSQ-zju** [Azure/MS-AMP#125]
Hello, thanks for your great work. I don't understand parts of the paper very clearly. Here is some questions.

> To equip tensor parallelism with FP8, we convert the sharded weight and activation tensors to FP8 format for linear layer computation.

1.If I don't use tensor parallelism, the liner weights are FP8 or FP16?
2.When forward and backward,  are all the weights FP8 to compute? (not master weights)

> g = g 1 ′′ + g 2 ′′ + · · · + g N''

3.and when compute **g** use this formula,  is the **g**  FP8 or FP16?  if it's FP8, will overflow occur?

**Comment by wkcn** [comment]
Hi @WeiSQ-zju , thanks for your attention to our work!
1. The master weight is an FP16 tensor with a scaling factor. It will be converted to the weight, which is an FP8 tensor with a scaling factor.
2. Yes. The weight for the computation is an FP8 tensor with a scaling factor.
3. **g** is an FP8 tensor without any scaling factor. The overflow may occur but we can decrease the scaling factor to reduce the overflow ratio, when quantifying a high-precision tensor to the FP8 tensor.

**Comment by WeiSQ-zju** [comment]
Thanks for your replay, the paper says that:

> g′i = µ · gi 
> If the ratio of the maximum value exceeds a specified threshold, i.e., 0.001%, µ is set to 1/2 in the subsequent training step, thereby mitigating the risk of overflow. Conversely, when the ratio consistently remains the threshold, we opt to exponentially increase µ to 2 over the span of 1,000 training steps, thereby effectively mitigating the risk of underflow occurrences

That's to say the overflow ratio of g'i is less than 0.001%, but when N is large, will the  overflow ratio of **g** is larger than 0.001%?

> g = g 1 ′′ + g 2 ′′ + · · · + g N''

**Comment by wkcn** [comment]
@WeiSQ-zju Sorry for late reply.

> That's to say the overflow ratio of g'i is less than 0.001%, but when N is large, will the overflow ratio of g is larger than 0.001%?

No. The overflow ratio is measured on `g` rather than `g'i`.

**Comment by tocean** [comment]
Close this issue since there are no activities for a long time
