### ISSUE TITLE
Huggingface Accelerate Support

### ISSUE THREAD

**Issue by muellerzr** [Azure/MS-AMP#128]
Hi all! I'm working on looking at this library as an alternative to transformers engine for the [accelerate project](https://github.com/huggingface/accelerate) and had a few general questions:

* One pain point with TE is HF models (such as Llama-2) have many custom layers to do ops that generally can be replaced with TE/FP8 specific ops, and as a result cannot be done OOTB easily. Have you tried your framework on models from HF? (Such as using `bloomz-3b` or `falcon-7b`). If so, does MS-AMP know the layers/ops to modify already? Or is there something specific we have do for each individual layer where it can be done.
* Does the framework support all FP8-compatible graphics cards? (e.g. can I test this on some local 4090's)

Looking forward to hearing back, we're very excited about this framework!

**Comment by muellerzr** [comment]
Update: I notice right now you just have support for `nn.Linear`, which makes sense why it works OOTB. Will test and see if I see increased throughput/less memory, I did not see this on models like `bloomz-3b` or `falcon-7b` if we only converted `nn.Linear`'s :)

**Comment by tocean** [comment]
Thanks for your attention to MS-AMP. 
Only replacing nn.Linear with te.linear or msamp.FP8Linear may not get good performance. If you want to improve throughput, you should use te.TransformerLayer for transformer-based model. For MS-AMP, it mainly focus on using FP8 to save memory and communication cost. Users can use both MS-AMP and Transformer Engine to save memory and accelerate training.  They are orthogonal.  Users can also increase micro batch size to improve throughput after using MS-AMP.

**Comment by muellerzr** [comment]
@tocean I think I'm almost ready for the base implementation/integration with Accelerate. One quick question:

You say they are orthogonal, but what is the recommended way to combine them? Should it be:

1. Replace `nn.Linear` and `nn.LayerNorm` with `te.Linear` and `te.LayerNorm` (`te.TransformerLayer` is harder to do automatically for Hugging Face models)
2. Call `model, optimizer = msamp.initialize(model, optimizer, opt_level=OPT_LEVEL)`?
