### ISSUE TITLE
Please update obsolete dependencies

### ISSUE THREAD

**Issue by rosario-purple** [Azure/MS-AMP#129]
This library is currently pinned to Flash Attention 1.0.9, Transformer Engine 0.11, and DeepSpeed 0.9.2. All of these are approximately six months old, and lack important new features (eg. DeepSpeed's Zero++). Please update the dependency versions, thanks :)

**Comment by skyshine102** [comment]
Same request. Would like to know if latest Deepspeed and Flash attention are compatible to MS-AMP.

**Comment by muellerzr** [comment]
Same request here, Accelerate requires at least 0.9.3 so this is a blocker on our end for integrating

**Comment by tocean** [comment]
We have update deepspeed to latest version.

**Comment by rosario-purple** [comment]
@tocean Thanks! Can flash-attn and transformer-engine also be updated? 1.0.9 and 0.11 are obsolete

**Comment by tocean** [comment]
> @tocean Thanks! Can flash-attn and transformer-engine also be updated? 1.0.9 and 0.11 are obsolete

Sure. I am working on that.

**Comment by tocean** [comment]
> @tocean Thanks! Can flash-attn and transformer-engine also be updated? 1.0.9 and 0.11 are obsolete

flash-attn is updated to 2.3.3, and transformer engine is updated to v1.1.
Looks like Megatron-LM can't converge with latest transformer engine(v1.2.1) but can converge with v1.1.

**Comment by skyshine102** [comment]
Hi @tocean, 
Do you know what's the cause of the convergence problem? I was wondering may we update flash-attn to v2.5.6?  I saw xformers and vllm projects all using flash-attn 2.5.6. And currently transformer engine v1.1's requirement will result in conflicts :(
