### ISSUE TITLE
Support for latest Megatron-LM and transformer-engine 1.0 +

### ISSUE THREAD

**Issue by sosofun** [Azure/MS-AMP#139]
Thank you for such a great and exciting project !

**What would you like to be added**:
Support for latest Megatron-LM and transformer-engine 1.0 +

**Why is this needed**:
 latest Megatron-LM support context-parallel and expert-parallel with transformer-engine 1.0+,  help train LLMs with long-context and moe model!

**Comment by tocean** [comment]
Thanks for your attention to our work. We will update Megatron-LM and transformer-engine to latest version.

**Comment by tocean** [comment]
I have updated the Transformer Engine to v1.1
