### ISSUE TITLE
Is MS-AMP reproducing the FP8-LM paper's results?

### ISSUE THREAD

**Issue by xrsrke** [Azure/MS-AMP#147]
Hi. Is MS-AMP reproducing the FP8-LM paper's results?

**Comment by tocean** [comment]
Hi,
For the performance numbers such as throughput, memory footprint, it can be reproduced.
For the training loss curve, we don't publish the data we use, so it can't not reproduced currently.

**Comment by xrsrke** [comment]
Ah thanks!!
