### ISSUE TITLE
[Question] How to apply MS-AMP to only part of the model?

### ISSUE THREAD

**Issue by veritas9872** [Azure/MS-AMP#163]
**What's the issue, what's expected?**:
I would like to apply MS-AMP to only parts of the model that are less sensitive to reduced precision.

**Additional information**:

Some parts of models are more sensitive to reduced precision than others but the current API makes it difficult to apply MS-AMP only to desired parts of the model. Is there an easy way of doing this?

**Comment by veritas9872** [comment]
Thanks! I will try it out!

**Comment by tocean** [comment]
Close this issue since there are no activities for a long time
