### ISSUE TITLE
Is activation checkpointing used for Table 5 from the FP8-LM paper?

### ISSUE THREAD

**Issue by SolitaryThinker** [Azure/MS-AMP#167]
Hi, 

I'm wondering if the TFLOPs/MFU numbers in table 5 of the paper is using activation checkpointing?

I've looked through the MS-AMP-Examples repo and it seems like GPT3 megatron does not have the --checkpoint-activations while the megatron-deepspeed scripts does. 

Thank you

**Comment by tocean** [comment]
Close this issue since there is no activities for a long time.
