### ISSUE TITLE
Clarification: do we need 20 or 16 bytes per parameter when training with Adam + Mixed precision 

### ISSUE THREAD

**Issue by rodrigo-f-nogueira** [Azure/MS-AMP#173]
Thanks for the great library.

In your recent paper, you mentioned that we need 16 bytes per parameter when training with Adam + Mixed precision (fp16)
https://arxiv.org/pdf/2310.18313.pdf

<img width="1143" alt="Screen Shot 2024-04-24 at 9 12 26 AM" src="https://github.com/Azure/MS-AMP/assets/121117945/c526fd8a-8c76-4b66-a60a-c9c1c1e93d63">

However, in the NLG-530B paper (https://arxiv.org/pdf/2201.11990), they mention we need 20 bytes per parameter:

<img width="990" alt="Screen Shot 2024-04-24 at 9 14 08 AM" src="https://github.com/Azure/MS-AMP/assets/121117945/5fce8536-db5f-4130-848c-6ecbd9dfb03a">

Could you please clarify which one is correct?

Perhaps we don't need the extra copy of weights and activations in fp16 (2+2 bytes) because we are casting 32->16bit everytime we do matmul?

**Comment by wkcn** [comment]
Hi @rodrigo-f-nogueira , thanks for your attention to our work!
The two statements are both correct. 

In our paper (FP8-LM), we consider the optimizer states (FP32 master weight + FP32 main gradient + two moments of Adam). The optimizer states exclude BF16 weight and BF16 weight gradient.
In NLG-530B, they considered all memory cost, including the optimizer states, weight and weight gradient.

**Comment by rodrigo-f-nogueira** [comment]
Great, thank you!
