### ISSUE TITLE
Why does using msamp decrease throughput

### ISSUE THREAD

**Issue by forevergj** [Azure/MS-AMP#175]
Why does the throughput of the CIFAR10 example in the project decrease when using deepspeed with MSAMP enable? Whether it is a forward process or a backward calculation process
MS-AMP enable：
![image](https://github.com/Azure/MS-AMP/assets/43092496/162237e8-6c28-43b0-ade0-b787df823c12)
MS-AMP close：
![image](https://github.com/Azure/MS-AMP/assets/43092496/dc571866-5252-4d69-943a-b4b1620ab04b)

**Comment by wkcn** [comment]
Hi @forevergj , thanks for your attention to our work!

When using MS-AMP, the quantization (BF16 -> FP8) and de-quantization (FP8 -> BF16) operations take extra time cost. It decreases the training throughput when training small models (< 1B parameters).

MS-AMP improves the throughput when training large models with more than 1B parameters.

**Comment by forevergj** [comment]
I am running a 1.8B model and the throughput drops by nearly half. Is this related to any operator?
> MS-AMP improves the throughput when training large models with more than 1B parameters.

**Comment by wkcn** [comment]
The de-quantization happens on the computation of FP8 Tensors, including FP8 weight gradients (`grad = grad_lp.float()`) and optimization states `exp_avg = exp_avg_lp.float(); exp_avg_sq = exp_avg_sq_lp.float()` (https://github.com/Azure/MS-AMP/blob/main/msamp/optim/adamw_base.py#L274).

It is adapted for both H100 and H800.

**Comment by forevergj** [comment]
tks a lot!!
