### ISSUE TITLE
nccl buildig failed without specifying NVCC_GENCODE  

### ISSUE THREAD

**Issue by tocean** [Azure/MS-AMP#44]
**What's the issue, what's expected?**:
nccl building failed if we don't specify NVCC_GENCODE. According to nccl documentation, specifying NVCC_GENCODE only speeds up the compiling. It should not fail even we don't pass NVCC_GENCODE.

**How to reproduce it?**:
```
git clone https://github.com/Azure/MS-AMP.git
cd MS-AMP
git submodule update --init --recursive
cd third_party/nccl
make -j src.build
```

**Log message or shapshot?**:
![image](https://user-images.githubusercontent.com/4133758/230781742-929d7f16-3a10-4de4-ae6b-e708210c026a.png)

**Additional information**:

**Comment by tocean** [comment]
We change from nccl to [msccl](https://github.com/Azure/msccl-executor-nccl) now. It will hang when building msccl without specifying NVCC_GENCODE. The latest msccl has solved this problem. Let's wait for the new release of msccl.

**Comment by yzygitzh** [comment]
> We change from nccl to [msccl](https://github.com/Azure/msccl-executor-nccl) now. It will hang when building msccl without specifying NVCC_GENCODE. The latest msccl has solved this problem. Let's wait for the new release of msccl.

Hi, to clarify, it's not hanging but due to build time very long (hours). It should succeed eventually. And the long build time issue is not solved in latest msccl.

**Comment by tocean** [comment]
Got it. Then this issue can not be reproduced with MSCCL. So close it.
