### ISSUE TITLE
`make postinstall` failed due to undeclared symbols.

### ISSUE THREAD

**Issue by guoshzhao** [Azure/MS-AMP#88]
**What's the issue, what's expected?**:
Build MSAMP failed due to can't find `ncclFp8E4M3` and `ncclFp8E5M2`. 

**How to reproduce it?**:
```
cd third_party/nccl
make -j src.build NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80"

apt-get update
apt install build-essential devscripts debhelper fakeroot
make pkg.debian.build
dpkg -i build/pkg/deb/libnccl2_*.deb

cd -
python3 -m pip install --upgrade pip
python3 -m pip install .
make postinstall
```

**Log message or shapshot?**:
![image](https://github.com/Azure/MS-AMP/assets/25875482/9c17a714-b948-4ac3-98d5-c81ecb28f9c6)

**Additional information**:

**Comment by wkcn** [comment]
The reason is that `ncclFp8E4M3` and `ncclFp8E5M2` are defined in NCCL with fp8-support (github.com/yzygitzh/nccl).
We should install NCCL with FP8-support first.

**Comment by wkcn** [comment]
> cd third_party/nccl
> make -j src.build NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80"
> sudo make install  # [new] install NCCL

**Comment by guoshzhao** [comment]
> > cd third_party/nccl
> > make -j src.build NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80"
> > sudo make install  # [new] install NCCL

Thanks, @tocean help to confirm and fix.

**Comment by tocean** [comment]
> > > cd third_party/nccl
> > > make -j src.build NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80"
> > > sudo make install  # [new] install NCCL
> 
> Thanks, @tocean help to confirm and fix.

Sure. The installation of NCCL will override the system nccl. T

> > > cd third_party/nccl
> > > make -j src.build NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80"
> > > sudo make install  # [new] install NCCL
> 
> Thanks, @tocean help to confirm and fix.

The root cause of this bug is that forgetting install libnccl-dev_2*.deb file.
